spring.application.name=order-management-api
spring.jpa.open-in-view=false

management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=when_authorized

spring.data.web.pageable.default-page-size=10
spring.data.web.pageable.max-page-size=50



