spring.datasource.url=jdbc:postgresql://db:5432/orderdb
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.flyway.enabled=true

jwt.secret=${JWT_SECRET:docker-secret-key-for-jwt-token-generation-and-validation-that-is-long-enough-for-production}
